[project]
name = "soup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "logfire>=4.15.1",
    "pydantic-ai>=1.21.0",
    "rich>=14.2.0",
]
